account/urls.py
from django.urls import path
from account.views import (
    login_view,
    logout_view,
    forgot_password_view,
    registeration_view,
    check_otp_view,
    check_reset_otp_view,
    reset_new_password_view,
)

app_name = 'account'  # Define the app namespace

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', registeration_view, name='register'),
    path('forgot-password/', forgot_password_view, name='forgot_password'),
    path('activate-email/', check_otp_view, name='activate_email'),
    path('reset-code/', check_reset_otp_view, name='reset_code'),
    path('new-password/', reset_new_password_view, name='reset_new_password'),
]

chatapp/urls.py
from django.urls import path
from chatapp import views

app_name = 'chatapp'  # Define the app namespace

urlpatterns = [
    path("", views.index, name="chat"),
    path("friend/<int:id>", views.friend, name="friend"),
]

web_chat_application/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("account/", include('account.urls')),
    path('chats/', include('chatapp.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

chatapp/models.py
from django.db import models

# Create your models here.


class Friend(models.Model):
    profile = models.OneToOneField("account.Profile", on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.profile.name

class ChatMessage(models.Model):
    body = models.TextField()
    msg_sender = models.ForeignKey("account.Profile", on_delete=models.CASCADE, related_name="msg_sender")
    msg_receiver = models.ForeignKey("account.Profile", on_delete=models.CASCADE, related_name="msg_receiver")
    seen = models.BooleanField(default=False)

    def __str__(self):
        return self.body
    

chatapp/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from chatapp.models import (Friend, ChatMessage)
from django.contrib.auth.models import User
# Create your views here.

@login_required
def index(request):
    user = request.user.profile
    user_friends = user.friends.all()
    contex = {
        "user": user,
        "user_friends": user_friends
    }
    return render(request, "chatapp/index.html", contex)

@login_required
@csrf_exempt
def friend(request,id):
    user = request.user.profile
    user_friends = user.friends.all()
    friend = Friend.objects.get(profile_id=id)

    chats = ChatMessage.objects.filter(
        msg_sender=user, msg_receiver=friend.profile).values()

    context = {
        "user_friends": user_friends,
        "friend": friend,
        "room_name" : "test"
    }
    return render(request, "chatapp/chatbox.html", context)

templates/chatapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/png" href="{% static 'imgs/web-icon.png' %}"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <title>Video Chat</title>
    
  </head>
  <body>
    {% block content %} {% endblock content %}

    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" ></script>
    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>

templates/chatapp/chatbox.html
{% extends "chatapp/index.html" %} 
{% load static %}
{% block chatbox %}
<div class="col-md-8">
  <div class="message-box">
    <div class="head-box-1">
      <ul class="msg-box list-inline text-left d-inline-block float-left">
        <li>
          <a href="{% url "chatapp:chat" %}" class="text-black">
            <i class="fas fa-arrow-left" id="back"></i>
          </a>
        </li>
        <li>
          <img src="{{friend.profile.pic.url}}" alt="profile image" class="img-fluid" width="40px" />
          <span>{{friend.profile.name}}</span>
        </li>
      </ul>

      <ul class="flat-icon list-inline text-right d-inline-block float-right">
        <li>
          <a href="#"> <i class="fas fa-video"></i> </a>
        </li>
        <li>
          <a href="#"> <i class="fas fa-camera"></i> </a>
        </li>
        <li>
          <a href="#" id="dset"> <i class="fas fa-ellipsis-v"></i> </a>
        </li>
      </ul>
    </div>

    <div class="msg_history">
      
    </div>

    <div class="send-message">
      <form id="send_messageForm">
        <textarea
          cols="10"
          rows="2"
          class="form-control"
          id="text_msgg"
          placeholder="Type your message here ..."
        >
        </textarea>
        <button type="submit" class="btn btn-primary" id="submit_chat">Send</button>
      </form>
    </div>
  </div>
</div>
{{ room_name|json_script:"room-name" }}
    <script>
        const roomName = '{{ room_name }}'

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + roomName
            + '/'
        );

        chatSocket.onopen = function (e) {
            console.log('WebSocket connection established.');
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        chatSocket.onmessage = function(e) {
          console.log("MEssage Received,...............");
        }

        document.querySelector('#text_msgg').onkeyup = function(e) {
            if (e.key === 'Enter') {  // enter, return
                document.querySelector('#submit_chat').click();
            }
        };

        document.querySelector('#submit_chat').onclick = function(e) {
            e.preventDefault()
            const messageInputDom = document.querySelector('#text_msgg');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message,
                'sender' : '{{request.user}}'
            }));
            messageInputDom.value = '';
        };

        chatSocket.addEventListener("message", (e) =>{
          const messageData = JSON.parse(e.data)
          console.log(messageData);

          var sender = messageData['sender'];
          var message = messageData['message'];
          
        // Here's where we append the message to the chatbox.
          var messageDiv = document.querySelector('.msg_history');
          if (sender != '{{request.user}}') { // assuming you have a variable `currentUser` to hold the current user's name
              messageDiv.innerHTML += `<div class="incoming_msg">
                                          <div class="received_withd_msg">
                                            <p>${message} - <b>${sender}</b></p>
                                            <span class="time_date"> 11:01 AM | June 9</span>
                                          </div>
                                        </div>`;
          } else {
              messageDiv.innerHTML += `<div class="outgoing_msg">
                                          <div class="sent_msg">
                                            <p>${message}</p>
                                            <span class="time_date"> 11:01 AM | June 9</span>
                                          </div>
                                        </div>`;
          }
        })
    </script>
{% endblock chatbox %}

templates/chatapp/index.html
{% extends "chatapp/base.html" %} {% block content %}
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="chat-list-box">
          <div class="head-box">
            <ul class="list-inline text-left d-inline-block float-left">
              <li>
                <img
                  src="{{request.user.profile.pic.url}}"
                  alt="profile picture"
                  class="img-rounded "
                />
              </li>
            </ul>
            <ul
              class="flat-icon list-inline text-right d-inline-block float-right"
            >
              <li>
                <a href="#"> <i class="fas fa-search"></i> </a>
              </li>
              <li>
                <a href="#"> <i class="fas fa-ellipsis-v"></i> </a>
              </li>
            </ul>
          </div>

          <div class="chat-person-list">
            <ul class="list-inline">
              {% for friend in user_friends %}
                <li>
                  <a href="{% url "chatapp:friend" friend.profile.pk %}" class="flip">
                    <img src="{{friend.profile.pic.url}}" alt="" />
                    <span>{{friend.profile.name}}</span>
                    <span class="chat-time">{{friend.profile.pk}}</span>
                  </a>
                </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
      <!-- col-md-4 closed -->

      {% block chatbox %}{% endblock chatbox %}
    </div>
  </div>
</section>
{% endblock content %}